const ACTIONS = {
    LOGIN:'LOGIN',
    LOGOUT:'LOGOUT',
    GETTOKEN:'GETTOKEN',
    USERAUTH:'USERAUTH',
    USERDETAILS:'USERDETAILS',
    USERPERSONALTASKS:'USERPERSONALTASKS',
    REQUIREDDATA:'REQUIREDDATA'
};

export default ACTIONS;